RDKCOM-1938 RDKBCMF-253 CcspEthAgent build errors
Emulator build is failing when all warnings are treated as errors in
meta-rdk-broadband/52095.
| ../../../../../../../../../../rdkb/components/opensource/ccsp/CcspEthAgent/source/TR-181/middle_layer_src/cosa_apis_util.c:1779:37: error: unused parameter 'ifname' [-Werror=unused-parameter]
|  int CosaUtilGetIpv6AddrInfo (char * ifname, ipv6_addr_info_t ** pp_info, int * p_num)
|

Reason for change: RDKBCMF-253 CcspEthAgent build errors
Test Procedure: None.
Risks: Low.
Signed-off-by: Stephen Barrett <stephen.barrett@accenture.com>

(cherry picked from commit e566a6adf076b651bd82ebda1f9f4824baafee2d)
(cherry picked from commit fe306e0becfb7d97417eca1d885f9873066018fc)
Change-Id: I13d217c073f974be674545b2da9521306586272e