RDKCOM-2367 RDKBCMF-279 CcspEthAgent build failure when WanManager is enabled
| CcspEthAgent/source/TR-181/board_sbapi/cosa_ethernet_apis.c:476:70: error: 'ETHWAN_DEF_INTF_NAME' undeclared (first use in this function); did you mean 'ETHWAN_DEF_INTF_NUM'?
|   476 |         v_secure_system(ip link set %s name %s,WAN_IF_NAME_PRIMARY,ETHWAN_DEF_INTF_NAME);
|       |                                                                      ^~~~~~~~~~~~~~~~~~~~

Reason for change: RDKBCMF-279 CcspEthAgent build failure when WanManager is enabled
Test Procedure: None.
Risks: Low.
Signed-off-by: Stephen Barrett <stephen.barrett@accenture.com>

(cherry picked from commit 850fbe4b6e33f55ae50376be5057a4792d6a9196)
Change-Id: I4e0b8e1a4d7a5a6a58e6fbdb8fedd46cd806dd5c