RDKCOM-2755: RDKBDEV-847: autotools cleanup
Reason for change:
 autotools cleanup
 add -lsecure_wrapper to libCcspEthAgent_board_sbapi_la_LDFLAGS
 add -lrt to libCcspEthAgent_board_sbapi_la_LDFLAGS
    Fix undefined reference to symbol 'mq_receive@@GLIBC_2.4'
 drop obsolete --with-ccsp-platform configure option
Test Procedure: Sanity.
Risks: None.
Signed-off-by: Andre McCurdy <armccurdy@gmail.com>

(cherry picked from commit b13acb0beb1610428abbb5204baedd5d0b3210b6)
Change-Id: I1d41fc8503ba416023efa5a8be418f818bc9bca1